
- name: Create a change request
  snow_record:
    state: present
    table: incident
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    data:
      state: present
      severity: "{{ sn_severity }}"
      Urgency: "{{ sn_priority }}"
      short_description: "Unwanted packag on server"
      error: Unreachable
      assigned_to: nikita
      Caller: test
  register: new_incident

- debug: 
    var: new_incident.record