
- name: Create a change request
  snow_record:
    state: present
    table: incident
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    data:
      severity: "{{ sn_severity }}"
      priority: "{{ sn_priority }}"
      short_description: "This is a test opened by Ansible"
  register: new_incident

- debug: 
    var: new_incident.record